root1 = Blogg::Category.create name: '1st cate root'
root1.children.create name: '1s son1'
root1.children.create name: '1s son2'
root1.children.create name: '1s son3'
root1.children.create name: '1s son4'
root1.children.create name: '1s son5'
root2 = Blogg::Category.create name: '2nd cate root'
root2.children.create name: '2s son1'
root2.children.create name: '2s son2'
root3 = Blogg::Category.create name: '3rd cate root'
root3.children.create name: '3s son1'
root3.children.create name: '3s son2'
root3.children.create name: '3s son3'
